### ISSUE TITLE
Not getting any readings overnight

### ISSUE THREAD

**Issue by alexmoir1** [JohanDegraeve/xdripswift#40] opened 2019-12-07 10:22 UTC
Can't get it to collect overnight despite having the app loaded at the front, all other apps closed & setting DND to off. Xdrip & testflight is always allowed. Any ideas?

**Comment by JohanDegraeve** [comment] 2019-12-07 11:06
First of all there's no need to keep the app at the front, no need to close other apps, as long as your Bluetooth is on then it should work.

This is only during the night ?

**Comment by alexmoir1** [comment] 2019-12-07 19:45
Mainly at night. Sometimes drops during the day.

**Comment by JohanDegraeve** [comment] 2019-12-07 20:06
what kind of transmitter ?
do you have a mac with xcode and a developper account ?
probably the only way to find out what happens is to follow the logs. At the moment the only way to do this is with xcode

**Comment by alexmoir1** [comment] 2019-12-07 22:22
MM1, sorry, don't have a mac

**Comment by JohanDegraeve** [comment] 2019-12-07 23:02
Ok no problem. 
Are you sure the MM is wel on placed on the sensor ? 
If it isn't you'll get a sensor not detected notification. 
That notification is removed as soon as there's a new reading.

can you test : setting missed reading alert to 6 minutes, if it goes off, then check if there's a 'sensor not detected' notification
(sorry that may keep you out of your sleep)

**Comment by alexmoir1** [comment] 2019-12-08 10:37
Switched to Android Xdrip last night & got the number OK all night. Will try ios with missed reading alert tonight.

**Comment by JohanDegraeve** [comment] 2019-12-08 11:45
if it works with Android then it looks like indeed there's something wrong with xdrip ios.
Strange however that there's not more complaints.

**Comment by MrrDonn** [comment] 2019-12-24 16:39
Hi guys! I am having the same problem as @alexmoir1 . Also pretty much no reading overnight. I also tried to kill all the other apps, did not help. iPhone is on the charger every night. During the day, the values are pretty much stable. I have up everyday with missing readings for 300+ minutes. 

The empty window starts usually at 2-3am and then when I wake up I have to restart xDrip. But sometimes it works overnight so I don't really understand it. 

But @JohanDegraeve  I do have a mac so I can try to do whatever may help us - but I don't know how :-). I really enjoy using this app, before I was on spike, but it was working terribly compared to xdrip.

**Comment by JohanDegraeve** [comment] 2019-12-24 18:28
I've been having the same problem actuallY. It's the same.
 It seems to be not every night.
I've been trying previous releases (because it's a recent problem i might have been caused by recent changes i did), but it's all the same.

I can only conclude that this is due to iOS13.  But then why not since the start of iOS13 (which was September i believe) ? I don't know.

Tonight I'll try to switch off NightScout upload. Who knows maybe iOS takes into account the battery consumption. Without Nightscout upload, the battery consumption should be minimal.

I'm also reviewing the missed reading alerts. Because I also find it strange that I'm not woken up by a missed reading alert. I'll make the missed reading alerts repeatable

**Comment by JohanDegraeve** [comment] 2019-12-24 18:33
@MrrDonn probably not necessary anymore to use Mac, as I've been experiencing the problem myself.
I checked myself and what i see is "Terminated due to signal 9"
but that doesn't give enough info. I was hoping to see an exception

**Comment by MrrDonn** [comment] 2019-12-24 21:32
So it is probably really ios thing, I was worried about that. iOS is acting weirdly since ios 12 I guess. I will try to turn off nightscout as well tonight. Although my nightscout credentials were wrong up until yesterday, I don't know if it has something in common, there were still missed readings... 
And I remember that Spike was doing the same thing, also not working overnight.
Still, if it was thing with battery drain, I don't understand why it does not kill the app during the day. Especially when the phone is changing the whole night.
But if you would give me some guidance I could try to do the mac log thing as well and maybe we could see something.

**Comment by JohanDegraeve** [comment] 2019-12-24 22:56
You would need to 'clone or download' (zip) : https://github.com/JohanDegraeve/xdripswift
(clone means you need to install git, for example if you install sourcetree for mac, you also get git. Probably easier to download the zip and unzip)
Instsall also cocoapods: open a terminal session (search for terminal), and type "sudo gem install cocoapods"
Then go to the folder where you've downloaded the project and type "pod install"
Install also xCode.
Then in Finder, double click on xdrip.xcworkspace 

You'll probably need a developer account further on. A bit a lot to explain here. Once you have a developer account and an app configured in iTunesConnect, a lot goes automatic
Once you're able to run xdrip on your phone, you can see all the logs.

**Comment by MrrDonn** [comment] 2019-12-25 11:25
Thank you @JohanDegraeve for this guidance! I will do it tonight. I am using DIY Loop so I have some experience with Xcode and I have the developer account. 

Btw I tried to turn off the nightscout upload tonight and got 100% of the readings. How about you?

**Comment by JohanDegraeve** [comment] 2019-12-25 11:57
I also turned off NightScout and there were no missed readings or crashes. I'll do this again the coming days

**Comment by MrrDonn** [comment] 2019-12-25 14:31
The same, if it was the case, do you know how to fix it?

**Comment by JohanDegraeve** [comment] 2019-12-25 15:39
If it's the case that iOS kills the app because it's consuming to much energy (when using NightScout), then I don't see how to solve this.

**Comment by MrrDonn** [comment] 2019-12-25 16:04
Understand. But why is it not happening during the day? Perhaps isn't is possible to kinda slow down the frequency of sending data to  nightscout?

**Comment by JohanDegraeve** [comment] 2019-12-25 21:20
Difficult to say what Apple exactly did for iOS13. 

Yes slowing down the frequency of uploading during the night would be an option.

**Comment by MrrDonn** [comment] 2019-12-26 14:20
Hi again, unfortunately, tonight I got a blank window again :/ Nightscout is off. Did not have the log going on, will do it tonight.

**Comment by JohanDegraeve** [comment] 2019-12-26 21:14
Hi, same here.
It's not a solution but I'm improving the missed reading alert. It will  be repeatable.

Thanks for verifying the logs

**Comment by JohanDegraeve** [comment] 2020-01-04 21:25
3.6.0 allows scheduling nightscout (and dexcom share) upload.
It allows to specify time intervals during which upload should be enabled/disabled

**Comment by alexmoir1** [comment] 2020-01-08 21:22
Hi Johan, is there a Nightscout update schedule that works without totally stopping uploads overnight?

**Comment by JohanDegraeve** [comment] 2020-01-08 21:41
no not that, you could schedule a change from on to off every 15 minutes

**Comment by JohanDegraeve** [comment] 2020-01-29 22:47
As additional guideline : what seems to have helped for me is to delete all unused or not frequently used apps from my iPhone. Strange but it seems to hep.

I will close this issue, I don't think there's anything else I can do

**Closed by JohanDegraeve** 2020-01-29 22:47 UTC
