### ISSUE TITLE
iOS 17 support

### ISSUE THREAD

**Issue by robinwo** [JohanDegraeve/xdripswift#455] opened 2023-08-24 12:03 UTC
I upgraded to the iOS 17 public beta, and since then, I've been unable to open xDrip.

It crashes automatically on opening the app. I tried reinstalling the app (built from source) using Xcode 15 (beta) with target iOS 17.

More people who tested & having this same issue?

**Comment by jonisaksson** [comment] 2023-08-24 12:07
I have been running iOS 17 since the first development beta (on version 7 i think now) without any problems at all with xdrip4iOS
But whenever you install a beta you know that you run the risk that it will break something.

**Comment by jonisaksson** [comment] 2023-08-24 13:50
By the way, i forgot. I did have some problems with building a new xdrip4iOS with the new Xcode beta, so I switched to Fastlane instead which worked a charm. Might be worth trying

**Comment by ricardosllm** [comment] 2023-08-31 09:47
Are there any docs on using Fastlane? I looked it up in the `Fastlane` dir, wiki here, and xdrip4ios.readthedocs.io but couldn't find it, would be happy to test it and even contribute to docs if needed.

**Comment by paulplant** [comment] 2023-09-01 10:14
https://github.com/JohanDegraeve/xdripswift/blob/master/fastlane/testflight.md

**Comment by LiroyvH** [comment] 2023-09-15 01:00
@robinwo Hi, I had the exact same problem. It was caused by a problem with AVAudioPlayer. For whatever weird reason, its not accepting some audio files (for some people, or some configurations don't attempt to play them (until an alarm is triggered (with specific parameters)) - including the sound played to keep xDrip awake in certain setups.

Re-encoding the audio files solved it for me so if needs be we'll just re-encode everything, though perhaps there's a better fix to work-around this with any audio file. Either way: hope we'll have time to get this fixed before the release on the 18th.

**Comment by paulplant** [comment] 2023-09-15 06:37
OK, making this a priority for today

**Comment by paulplant** [comment] 2023-09-15 15:33
Working on this with Liroy now. Only apps that are built and installed via Xcode seem to be affected by this issue.

It seems that Testflight and App Store releases (Shuggah) are unaffected by the AVAudioPlayer() issue related to .mp3 soundfiles.

The mp3 files are being reencoded to a compatible format.

**Comment by paulplant** [comment] 2023-09-16 16:40
Fixed by #459

**Closed by paulplant** 2023-09-16 16:40 UTC
