### ISSUE TITLE
Every Alarm causes entry in Apple health

### ISSUE THREAD

**Issue by hansdampf01** [JohanDegraeve/xdripswift#133] opened 2020-07-25 22:56 UTC
It seems that every Alarm is causing a new entry in Apple Health (probably in Nightscout too?) e.g. I'm getting normal reading shortly after high warning and a few second later another high alarm which causes several entries every few minutes.

E.g: all entries are pulled from Apple Health - only xDrip4iOS is writing BG data to Apple Health

 ![image](https://user-images.githubusercontent.com/55264284/88467750-b39fad00-ceda-11ea-9a2a-3e2dcecc753e.png)

**Comment by JohanDegraeve** [comment] 2020-07-26 15:28
I was not able to reproduce this.

are you using MM or Bubble ?
Especially MM has the habit to disconnect/reconnect very often. If this happens, a new reading will be created. Normally there should be maximum 2 readings in one minute. 

Could you send an issue report and mention the issue number in the problem description ?

**Comment by hansdampf01** [comment] 2020-07-26 15:44
Just sent. Im using mm2 (fw 7)

**Comment by JohanDegraeve** [comment] 2020-07-26 19:49
It's indeed the MM2 that disconnects/connects frequently, it gets new readings. The same happens if you go to the Bluetooth peripheral tab and disconnect/connect , or switch off/on bluetooth.
You will immediately get a new reading.

If you send the issue report to yourself, then in an edit view the file xdriptrace.0.log, in that file search for 'didDisconnect', you will see it happens a lot during the periods you have all those readings in healthkit

What is not correct here is that you seem to have more than 2 readings in 1 minute sometimes. Normally it should not give new readings if the latest was less than 30 seconds ago. I'll see if I can check that, I'm on Dexcom for the moment

**Comment by JohanDegraeve** [comment] 2020-08-16 13:34
I'm closing this one.
I could reduce the number of readings in HS to maximum 1 per

**Closed by JohanDegraeve** 2020-08-16 13:34 UTC
