### ISSUE TITLE
4.11.0 Won't connect to Bluetooth

### ISSUE THREAD

**Issue by ricardosllm** [JohanDegraeve/xdripswift#416] opened 2023-01-18 09:56 UTC
Hi, I've tried to update to 4.11 and connect a new eu Libre 2 but I can't connect. 

---

iPhone 14 Pro 
eu Libre 2
My own apple developer account 
git commit:
```
commit 4be086a84dcf4886341b1b7f3741762dbc090aec (HEAD -> master, origin/master, origin/develop, origin/HEAD)
Author: Johan Degraeve <johan.degraeve@gmail.com>
Date:   Thu Jan 12 21:25:09 2023 +0100

    force treatments sync re-enabled, was commented out temporary
```
---

I'm able to build as normal, I manage to scan successfully, usually after a few tries, but it then gets stuck in `Scanning`. 

I've tried to 
1. scan the sensor with librelink - succeeded - then kill the librelink app 
2. `Clean Build Folder`,
3. `rm -rf Pods` then `pod install`
4. I've checked that my git diff does not show anything
5. My config is there and working correctly - I can sign 
6. reboot my iPhone a few times
7. put all other "old" sensors in the house in the microwave
8. I've even tried Shuggah, which I never had to before - still the same issue on the same version, 4.11.0

The one thing I haven't tried was uninstalling the app from my iphone as to not loose my historical data, I guess that is the next step. 

Here's the output on Xcode of a "successful" launch and scan, it then got stuck as describe above. 

```
xdrip(526,0x1e5d7bc00) malloc: nano zone abandoned due to inability to preallocate reserved vm space.
2023-01-18 10:43:58.917210+0100 xdrip[526:21457] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-01-18 10:43:58.917359+0100 xdrip[526:21457] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-01-18 10:43:58.917409+0100 xdrip[526:21457] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-01-18 10:43:58.926325+0100 xdrip[526:21457] [Assert] UINavigationBar decoded as unlocked for UINavigationController, or navigationBar delegate set up incorrectly. Inconsistent configuration may cause problems. navigationController=<xdrip.TreatmentsNavigationController: 0x109124680>, navigationBar=<UINavigationBar: 0x108c2b900; frame = (0 44; 0 50); opaque = NO; autoresize = W; layer = <CALayer: 0x107473f90>> delegate=0x109124680
2023-01-18 10:43:58.927209+0100 xdrip[526:21457] [Assert] UINavigationBar decoded as unlocked for UINavigationController, or navigationBar delegate set up incorrectly. Inconsistent configuration may cause problems. navigationController=<xdrip.BluetoothPeripheralNavigationController: 0x109123480>, navigationBar=<UINavigationBar: 0x108c32c80; frame = (0 44; 0 50); opaque = NO; autoresize = W; backgroundColor = UIExtendedGrayColorSpace 0.1 1; layer = <CALayer: 0x107479900>> delegate=0x109123480
2023-01-18 10:43:58.928300+0100 xdrip[526:21457] [Assert] UINavigationBar decoded as unlocked for UINavigationController, or navigationBar delegate set up incorrectly. Inconsistent configuration may cause problems. navigationController=<xdrip.SettingsNavigationController: 0x109122e80>, navigationBar=<UINavigationBar: 0x108c32200; frame = (0 44; 0 50); opaque = NO; autoresize = W; backgroundColor = UIExtendedGrayColorSpace 0.1 1; layer = <CALayer: 0x10747aec0>> delegate=0x109122e80
2023-01-18 10:43:58.981533+0100 xdrip[526:21457] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x106f20440> (Domain: group.com.522ZQ9PP9J.loopkit.LoopGroup, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
CoreData: annotation: Core Data multi-threading assertions enabled.
2023-01-18 10:43:58.987453+0100 xdrip[526:21736] [WC] WCSession counterpart app not installed
2023-01-18 10:43:58.996316+0100 xdrip[526:21457] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-01-18 10:44:12.294481+0100 xdrip[526:21457] [CoreNFC] -[NFCTagReaderSession setAlertMessage:]:101 (null)
2023-01-18 10:44:15.608112+0100 xdrip[526:21457] [Presentation] Attempt to present <UIAlertController: 0x109113280> on <UITabBarController: 0x10783ca80> (from <xdrip.BluetoothPeripheralViewController: 0x10786ae80>) which is already presenting <UIAlertController: 0x109142c80>.

```

Is there anyting else I can provide? 

Been using xdrip4ios with Libre 2 for over a year with no issues. 
Yesterday I had 2 sensors that were broken, I validated that in the librelink app, but I still tried to connect them to xdrip4ios, not sure that caused anything.

---

Managed to scan successfully
![IMG_5683](https://user-images.githubusercontent.com/5474201/213154273-d64b7bbc-06bb-4d4e-8435-a8db2cdf2a72.PNG)

But then it's stuck in this stage
![IMG_5684](https://user-images.githubusercontent.com/5474201/213154264-f0c26259-eb4c-4824-a1c2-6071f58ed72f.PNG)

**Comment by paulplant** [comment] 2023-01-19 15:52
I'm a little confused. Is this an actual problem with the build or project code? Or are you just having trouble connecting a Libre 2? Normal tech support is usually covered in the Facebook group and we leave Github for development work.

https://www.facebook.com/groups/853994615056838

The most obvious thing would be that they have given you a Libre 1 sensor or something. When xDrip4iOS is totally unable to find any sensors when scanning via BLE, the issue is nearly always that the user still has the sensor connected to another app (unlikely in your case), or that the pharmacy/hospital has given them a Libre 1 by mistake. Can you provide the first 5 digits of the sensor serial number?

**Comment by paulplant** [comment] 2023-01-23 14:11
@ricardosllm - please advise if this is a bug with the app, or if you just needed technical help connecting. It is to know if we should close this issue, or not.

**Comment by paulplant** [comment] 2023-01-26 18:05
@ricardosllm - please reply or we will close this issue. Thanks.

**Closed** 2023-01-30 10:54 UTC
